[package]
name = "oracle"
version = "0.1.0"
edition = "2024"
description = "Smart Escrow example that unlocks when oracle price data meets specified threshold conditions"
license = "ISC"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
xrpl-std = { path = "../../../../xrpl-std" }
